export class User {

  public message!: string;
  public id!: number;
  public trnid!: number;
  public username!: string;
  public password!: string;
  public firstName!: string;
  public lastName!: string;
  public mainmenulabel!: string;
  public userid!: number;
  public token!: string;
  public dbName!: string;
  public companycode!: number;
  public usergroupid!: string;
  public landpage!: string;
  public fullname!: string;
  public companyName!: string;
  public companyLogo!: string;
  public pagename!: string;
  public zoneid!: number;
  public regionid!: number;
  public accessToken!: string;
  public areaid!: number;
  public mastername!: string;
  public terrid!: number;
  public patchid!: number;
  public noofdays!: number;
  public userId!: number;
  public employeecode!: string;
  public productlstnumber: [] = [];
  public resourceName!: string;
  public meetingid!: number;
  public designation!: string;
  public LoginName: any;
  public formname!: string;
  public cancreateproject!: string;
  public isreporting!: string;
  public fullnamefortoggal!: string;
  public reportingmanager!: number;
  public alert!: string;
  public department!: string;
  public band!: string;
  public toggle!: string;
  // useridmenu!: string;
  // pageno!: number;
  // reshead!: string;
  typeidq!: any;
  public useridmenu!: string;
  public pageno!: number;
  public reshead!: string;
  public userID!: number;
  public totalItems!: number;
  public searchText!: string;
  public toDisplay!:boolean;
  public bactid!: number;
  public code!: String;
  public shortname!: String;
  public value!: String;
  public type!: String;
  public typeid!: number;
  public activeStatus!: string;
  public adduserid!: number;
  public edituserid!: number;
  public adddate!: number;
  public editdate!: number;
  public chkselect!: string;
  public add!: string;
  public edit!: string;
  public delete!: string;
  public view!: string;
  public approve!: string;
  public microbe!: string;

}